/*
** gamestoragefile.cpp
** Separate file for console variables intended for storage
**
**---------------------------------------------------------------------------
** Copyright 1998-2008 Randy Heit
** Copyright 2017-2025 GZDoom Maintainers and Contributors
** Copyright 2025 UZDoom Maintainers and Contributors
** All rights reserved.
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions
** are met:
**
** 1. Redistributions of source code must retain the above copyright
**    notice, this list of conditions and the following disclaimer.
** 2. Redistributions in binary form must reproduce the above copyright
**    notice, this list of conditions and the following disclaimer in the
**    documentation and/or other materials provided with the distribution.
** 3. The name of the author may not be used to endorse or promote products
**    derived from this software without specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
** IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
** OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
** IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
** INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
** NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OFf
** THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**---------------------------------------------------------------------------
**
*/

#include "c_cvars.h"
#include "doomstat.h"
#include "gamestoragefile.h"
#include "i_specialpaths.h"
#include "m_argv.h"
#include "version.h"

FARG(globalstorage, "Configuration", "Specifies an alternative global storage file to use.", "storagefile",
	"Causes " GAMENAME " to use an alternative global storage file. If storagefile does not exist,"
	" it will be created.");

FGameStorageFile::FGameStorageFile ()
{
	FString pathname;

	OkayToWrite = false;
	bModSetup = false;

	pathname = GetStoragePath();
	ChangePathName(pathname.GetChars());
	LoadConfigFile();

	if (FileExisted)
	{
		// We had this file before, always write it back out
		SetHaveStorage();
	}
}

FGameStorageFile::~FGameStorageFile()
{
}

void FGameStorageFile::WriteCommentHeader(FileWriter *file) const
{
	file->Printf("# This file was generated by " GAMENAME " %s on %s\n", GetVersionString(), myasctime());
}

void FGameStorageFile::DoGameSetup(const char *gamename)
{
	const char *key;
	const char *value;

	sublen = countof(section) - 1 - mysnprintf (section, countof(section), "%s.", gamename);
	subsection = section + countof(section) - sublen - 1;
	section[countof(section) - 1] = '\0';

	strncpy (subsection, "Unknown", sublen);
	if (SetSection(section))
	{
		ReadCVars(0);
	}

	strncpy (subsection, "User", sublen);
	if (SetSection(section))
	{
		ReadCVars(0);
	}

	strncpy (subsection, "Server", sublen);
	if (SetSection(section))
	{
		ReadCVars(0);
	}

	strncpy (subsection, "Local", sublen);
	if (SetSection(section))
	{
		ReadCVars(0);
	}
}

// Like DoGameSetup(), but for mod-specific cvars.
// Called after CVARINFO has been parsed.
void FGameStorageFile::DoModSetup(const char *gamename)
{
	mysnprintf(section, countof(section), "%s.User.Mod", gamename);
	if (SetSection(section))
	{
		ReadCVars(CVAR_MOD|CVAR_USERINFO|CVAR_IGNORE);
	}
	mysnprintf(section, countof(section), "%s.Server.Mod", gamename);
	if (SetSection (section))
	{
		ReadCVars (CVAR_MOD|CVAR_SERVERINFO|CVAR_IGNORE);
	}
	mysnprintf(section, countof(section), "%s.Local.Mod", gamename);
	if (SetSection (section))
	{
		ReadCVars (CVAR_MOD|CVAR_CONFIG_ONLY|CVAR_IGNORE);
	}
	// Signal that these sections should be rewritten when saving the config.
	bModSetup = true;
}

// Read cvars from a cvar section of the ini. Flags are the flags to give
// to newly-created cvars that were not already defined.
void FGameStorageFile::ReadCVars(uint32_t flags)
{
	const char *key, *value;
	FBaseCVar *cvar;
	UCVarValue val;

	flags |= CVAR_STORAGE|CVAR_ARCHIVE|CVAR_UNSETTABLE|CVAR_AUTO;
	while (NextInSection (key, value))
	{
		cvar = FindCVar (key, NULL);
		if (cvar == NULL)
		{
			cvar = new FStringCVar (key, NULL, flags);
		}
		val.String = const_cast<char *>(value);
		cvar->SetGenericRep(val, CVAR_String);
	}
}

void FGameStorageFile::ArchiveGameData(const char *gamename)
{
	char section[32*3], *subsection;

	sublen = countof(section) - 1 - mysnprintf (section, countof(section), "%s.", gamename);
	subsection = section + countof(section) - 1 - sublen;

	strncpy(subsection, "User", sublen);
	SetSection(section, true);
	ClearCurrentSection();
	C_ArchiveCVars(this, CVAR_STORAGE|CVAR_ARCHIVE|CVAR_USERINFO);

	if (bModSetup)
	{
		strncpy (subsection, "User.Mod", sublen);
		SetSection(section, true);
		ClearCurrentSection();
		C_ArchiveCVars(this, CVAR_MOD|CVAR_AUTO|CVAR_STORAGE|CVAR_ARCHIVE|CVAR_USERINFO);
	}

	// Do not overwrite the serverinfo section if playing a netgame, and
	// this machine was not the initial host.
	if (!netgame || consoleplayer == 0)
	{
		strncpy(subsection, "Server", sublen);
		SetSection(section, true);
		ClearCurrentSection();
		C_ArchiveCVars(this, CVAR_STORAGE|CVAR_ARCHIVE|CVAR_SERVERINFO);

		if (bModSetup)
		{
			strncpy (subsection, "Server.Mod", sublen);
			SetSection (section, true);
			ClearCurrentSection ();
			C_ArchiveCVars (this, CVAR_MOD|CVAR_AUTO|CVAR_STORAGE|CVAR_ARCHIVE|CVAR_SERVERINFO);
		}
	}

	strncpy(subsection, "Local", sublen);
	SetSection(section, true);
	ClearCurrentSection();
	C_ArchiveCVars(this, CVAR_AUTO|CVAR_STORAGE|CVAR_ARCHIVE|CVAR_CONFIG_ONLY);

	if (bModSetup)
	{
		strncpy(subsection, "Local.Mod", sublen);
		SetSection(section, true);
		ClearCurrentSection();
		C_ArchiveCVars(this, CVAR_MOD|CVAR_AUTO|CVAR_STORAGE|CVAR_ARCHIVE|CVAR_CONFIG_ONLY);
	}

	strncpy(subsection, "Unknown", sublen);
	SetSection(section, true);
	ClearCurrentSection();
	C_ArchiveCVars(this, CVAR_AUTO|CVAR_STORAGE|CVAR_ARCHIVE);
}

FString FGameStorageFile::GetStoragePath()
{
	const char *pathval;

	pathval = Args->CheckValue(FArg_globalstorage);
	if (pathval != NULL)
	{
		return FString(pathval);
	}

	return M_GetSavegamesPath() + "storage.ini";
}

void FGameStorageFile::SetHaveStorage()
{
	// Don't write storage.ini at all until we ever
	// load a mod / IWAD that uses the feature.
	OkayToWrite = true;
}

bool FGameStorageFile::HaveStorage()
{
	return OkayToWrite;
}
